# Generated by Django 3.2.18 on 2023-03-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_is_manager1_user_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_manager1',
        ),
    ]
