# Generated by Django 3.2.18 on 2023-03-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('age', models.PositiveIntegerField()),
                ('joiningDate', models.DateField()),
                ('birthDate', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=100)),
                ('pPrice', models.FloatField()),
                ('pQty', models.IntegerField()),
                ('pDesc', models.CharField(max_length=100, null=True)),
                ('pStatus', models.BooleanField(default=True)),
                ('pColor', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
