# Generated by Django 3.2.18 on 2023-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_addfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
